# 1-D How to create an array?

In [1]:
import numpy as np
a = np.array ([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [2]:
b = np.zeros (2)
b

array([0., 0.])

In [4]:
c = np.ones (3)
c

array([1., 1., 1.])

In [6]:
# Create an empty array with 2 elements
d = np.empty (3)
d

array([1., 1., 1.])

# 02_1-D How to Create an array?

In [8]:
# with range of elements
e = np.arange (6)
e

array([0, 1, 2, 3, 4, 5])

In [9]:
# with specific range of elements
f  = np.arange (2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [10]:
# skips .. continue...
g = np.arange (2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# linerly spaced arrays
h = np.linspace (0, 10,num = 5) # Gives Use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 03_1-D How to create an array?

In [15]:
# specific data types in array
i = np.ones (5, dtype = np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [16]:
j = np.ones (3, dtype = np.float64)
j

array([1., 1., 1.])

# 2-D How to create an array?

In [17]:
np.zeros ((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones ((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.empty ((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3-D How to create an array?

In [20]:
# making and reshaping a 3D array
c = np.arange (24).reshape (2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])